/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0xQT0cwUzNCMkgxRTBFbDhqbEJrL3ZDcDgyNEVEdlVSaGFlN3ZaVnkycz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic2lUMThEV3N0RldLYjQ2aHZGQ0xCaHBlb3gzTDBzYXFEZm9oZjdSbThRMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhUEpHYmJueHZzRUFWYTc4RzJldUV3RWlEOU8yZzRuekpBVzdmU1dSckZjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0d2R5TTRtZmw5T21rbWUrTy9rb3lDczdDd29JMERiY2RtZE1LajRCNW00PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFHeThuUW9iS0FoeFQ4KzBjNCtLZHdOZUJPUEdpTzlmejFhMXpKaUtNV289In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBWQWlOYXAwek5hZmt1d1VWUHZma1Z1eWZmVkpGVlp5SUhlUTd3TGRzRWM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEo2UW5qSlNKM1RudjVDTjg0OXo3SVlRNEViazEwS2VOeFAxN08zRHpXRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiemQvbFlvWTdGejFCaDZpMENEbmJvL0FGbXFhVzJTU2xNcGlLZmwwbkpYTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZRbnlIcGRhT1oxOVIzVnpjVkpGdkJnaTI3OUtIcnN1SW1nYVllWEVZakdtOGZjNUJweHRnWE1ZMjdmWi92eXRYamRwMS91Y0dtT01rWDJpSnZXOWl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODksImFkdlNlY3JldEtleSI6Ijd0UVhlV3VrL1R4Z1M1SjlMS0FTV0Z6Q2VNcGN4UDdzS2gwMzI4QkFmaDg9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQwOTU1NDY2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjZGQkVDQzlERjdEQzQ2NTU5QjZFM0U0OUIwQ0RBQ0E5In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzI3OTI1NDh9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0MDk1NTQ2NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3RjBFQUU0MkI2QjYzOEIxRTQ5NzEyQjYyODVDMzU1OSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMyNzkyNTU0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3RXoyYzRQNlI4cUdfaU55WkIxTVdBIiwicGhvbmVJZCI6IjA2NGU5YzQ5LWM0ZTYtNDk0My1iMmJmLWJhN2Y3MDgzNTk2MCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGNFZTVDUxbi82QTh0ajZMY3VhdlZPR1VIS1E9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUdVQkdWVFI3YlNpamIvemlZK1pUM0s5NERjPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IllSTDJLSFNOIiwibWUiOnsiaWQiOiIyNTQ3NDA5NTU0NjY6NDFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSmVzc2llIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMZXgrZTRERU11aG9ib0dHQVFnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ5a1ZrUkZFT3ZPUTJUSHRRVklOeVFwVnJ2R2hHSSsxM0Fydk1WS1NXSTN3PSIsImFjY291bnRTaWduYXR1cmUiOiJDR1VEVzhjNnJvYXhDVnZkajFHaUQ1NCtvYjNKSDZVWGpCOGtLMHE4a25Ua05vdHdrTnJMMzd1WEsxUHBOcFQrQWpMTmxJOFNma0VHNFBMUUtFbnZBZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiT2tOMU5NeHpmWTRtWlZwb0dWMTJmZzBPYkpaek9SeXFuTFQyRTZzeEV0Ujg1UERzRkl3dTBiQmVJeFY5b2RsK2pkbGJ3WnZPVVZiNi9lUEltVUtiZ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NDA5NTU0NjY6NDFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCY3BGWkVSUkRyemtOa3g3VUZTRGNrS1ZhN3hvUmlQdGR3Szd6RlNrbGlOOCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjc5MjUzNywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFLcEMifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
